### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by dewshr** [raphael-group/NAIBR#17]
Memory usage is less than the total assigned, but its giving me Memory error.
`Resource usage summary:

    CPU time :                                   130080.91 sec.
    Max Memory :                                 179960 MB
    Average Memory :                             64903.62 MB
    Total Requested Memory :                     200000.00 MB
    Delta Memory :                               20040.00 MB
    Max Swap :                                   73 MB
    Max Processes :                              3
    Max Threads :                                31
    Run time :                                   122867 sec.
    Turnaround time :                            123796 sec.`

Traceback (most recent call last):

  File "NAIBR.py", line 88, in <module>
    main()
  File "NAIBR.py", line 74, in main
    cands,p_len,p_rate = get_candidates(discs,reads_by_LR)
  File "src/get_reads.py", line 152, in get_candidates
    p_len,p_rate,barcode_overlap = get_distributions(reads_by_LR)
  File "src/distributions.py", line 115, in get_distributions
    get_overlap(barcode_LRS)
  File "src/distributions.py", line 99, in get_overlap
    barcode_overlap[(chr1,id1,chr2,id2)] += 1

MemoryError

**Comment by relyanow** [comment]
I will look into this. It is strange that the max memory is less than the requested memory but you're still running into the MemoryError. It might take some time to figure out.

In the meantime, you could try splitting the file by chromosome and running separately on each chromosome. This should hopefully not run into any memory issues. The only downside to this approach is you won't be able to discover interchromosomal translocations.
