### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by mzwaig** [raphael-group/NAIBR#18]
Hello,

I had the same issue as in #17 but I managed to run NAIBR on most of my samples by giving it lost of processors (16 or more) but only 1 threads.

For one sample, I'm getting an additional error (assert len(lengths)>100) and I'm not sure why.

Here's the log file

Traceback (most recent call last):
  File "/lb/project/Melissa-abacus/tools/NAIBR/NAIBR.py", line 90, in <module>
    main()
  File "/lb/project/Melissa-abacus/tools/NAIBR/NAIBR.py", line 61, in main
    data = parallel_execute(run_NAIBR,chroms)
  File "/lb/project/Melissa-abacus/tools/NAIBR/src/utils.py", line 395, in parallel_execute
    data = map(function,input_list)
  File "/lb/project/Melissa-abacus/tools/NAIBR/NAIBR.py", line 35, in run_NAIBR
    cands,p_len,p_rate = get_candidates(discs,reads_by_LR)
  File "/lb/project//Melissa-abacus/tools/NAIBR/src/get_reads.py", line 154, in get_candidates
    p_len,p_rate,barcode_overlap = get_distributions(reads_by_LR)
  File "/lb/project/Melissa-abacus/tools/NAIBR/src/distributions.py", line 120, in get_distributions
    p_len = get_length_distr(LRs)	
  File "/lb/project/Melissa-abacus/tools/NAIBR/src/distributions.py", line 126, in get_length_distr
    assert len(lengths)>100
AssertionError

Thanks for you help,
Melissa

**Comment by zuzanahalenkova** [comment]
Hello, I have encountered the same error, did you manage to overcome it somehow?
Thank you for your help,
Zuzana

**Comment by pontushojer** [comment]
@zuzanahalenkova I implemented a fix to what possibly could be the issue here in the PR #23. Try it out and see if that works.
