### ISSUE TITLE
Only work for chr21?

### ISSUE THREAD

**Issue by Reedwarbler** [raphael-group/NAIBR#2]
Hi,

I think line 49 in NAIBR.py should not be:
```
data = parallel_execute(run_NAIBR,['chr21'])
```
I have an alignment with chromosome names: 1,2,3,4,...,X, Y, so I change a little bit of the code to feed in the chromosome names, but met the following issue. Would you please help to check any possible reason cause this?
```
Traceback (most recent call last):
  File "NAIBR.py", line 79, in <module>
    main()
  File "NAIBR.py", line 54, in main
    data = parallel_execute(run_NAIBR, chroms_picked)
  File "src/utils.py", line 385, in parallel_execute
    data = map(function,input_list)
  File "NAIBR.py", line 28, in run_NAIBR
    cands,p_len,p_rate = get_candidates(discs,reads_by_LR)
  File "src/get_reads.py", line 149, in get_candidates
    p_len,p_rate,barcode_overlap = get_distributions(reads_by_LR)
  File "src/distributions.py", line 110, in get_distributions
    p_rate = get_rate_distr(LRs)
  File "src/distributions.py", line 136, in get_rate_distr
    alpha,loc,beta = scipy.stats.gamma.fit(rate)
  File "/home/new_virtualenv/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 2044, in fit
    return super(gamma_gen, self).fit(data, *args, **kwds)
  File "/home/new_virtualenv/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2185, in fit
    start = self._fitstart(data)
  File "/home/new_virtualenv/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 2033, in _fitstart
    return super(gamma_gen, self)._fitstart(data, args=(a,))
  File "/home/new_virtualenv/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2023, in _fitstart
    loc, scale = self._fit_loc_scale_support(data, *args)
  File "/home/new_virtualenv/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2253, in _fit_loc_scale_support
    data_a = np.min(data)
  File "/home/new_virtualenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2372, in amin
    out=out, **kwargs)
  File "/home/new_virtualenv/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```
The content of configuration file：
```
# minimum mapping quality (default=40)
min_mapq=30

# input bam file
bam_file=/n/data1/Alignment_longranger_wgs/outs/phased_possorted_bam.bam

# output directory (default=.)
outdir=results

# list of intervals not to be intcluded in analysis (default=None)
blacklist=None

# list in BEDPE format of novel adjacencies to be scored by NAIBR (default=None)
candidates=None

# maximum distance between read-pairs in a linked-read (default=10000)
d=10000

# minimum size of structural variant (default=lmax)
min_sv=500

# number of cores (default=1)
cores=15

# minimum number of barcode overlaps supporting a candidate NA (default = 3)
k=3
```

**Comment by relyanow** [comment]
Thanks for noticing that. Indeed, the code should run on all chromosomes. I pushed a new commit that should fix the error you were getting. I think it is caused by improper handling of a chromosome that has no reads. Let me know if the error persists.

**Comment by Reedwarbler** [comment]
Hi, is it normal for running more than 20hrs and there is no any output? I have one alignment from longranger with coverage around 40X.

**Comment by relyanow** [comment]
This seems long if you are running on 15 cores. I would expect it to take about 5 hours. However, if your dataset is heavily rearranged then this may increase the running time. You can restrict the number of potential structural variants by increasing either k (the minimum number of barcode overlaps required) or min_discs (the minimum number of discordant reads required) which will decrease the running time. You should also get some output as the program is running (it should print 'ranking [# candidates] candidates from [chromosome]').
