### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by fangli0813** [raphael-group/NAIBR#3]
Hi, I met this issue while running NAIBR: 

/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:409: RuntimeWarning: Mean of empty slice.
  mu = data.mean()
/home/lifang/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:410: RuntimeWarning: Mean of empty slice.
  m2 = ((data - mu)**2).mean()
/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:411: RuntimeWarning: Mean of empty slice.
  m3 = ((data - mu)**3).mean()
/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:2300: RuntimeWarning: Mean of empty slice.
  muhat = tmp.mean()
/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:2301: RuntimeWarning: Degrees of freedom <= 0 for slice
  mu2hat = tmp.var()
/home/lifang/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/lifang/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/lifang/software/NAIBR/src/NAIBR.py", line 79, in <module>
    main()
  File "/home/lifang/software/NAIBR/src/NAIBR.py", line 53, in main
    data = parallel_execute(run_NAIBR,chroms)
  File "/home/lifang/software/NAIBR/src/utils.py", line 385, in parallel_execute
    data = map(function,input_list)
  File "/home/lifang/software/NAIBR/src/NAIBR.py", line 32, in run_NAIBR
    cands,p_len,p_rate = get_candidates(discs,reads_by_LR)
  File "/home/lifang/software/NAIBR/src/get_reads.py", line 150, in get_candidates
    p_len,p_rate,barcode_overlap = get_distributions(reads_by_LR)
  File "/home/lifang/software/NAIBR/src/distributions.py", line 111, in get_distributions
    p_rate = get_rate_distr(LRs)
  File "/home/lifang/software/NAIBR/src/distributions.py", line 136, in get_rate_distr
    alpha,loc,beta = scipy.stats.gamma.fit(rate)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 2036, in fit
    return super(gamma_gen, self).fit(data, *args, **kwds)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2185, in fit
    start = self._fitstart(data)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 2025, in _fitstart
    return super(gamma_gen, self)._fitstart(data, args=(a,))
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2023, in _fitstart
    loc, scale = self._fit_loc_scale_support(data, *args)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2253, in _fit_loc_scale_support
    data_a = np.min(data)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2352, in amin
    out=out, **kwargs)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

Thank you!

**Comment by relyanow** [comment]
Can you post the config file you used for this run? Also try pulling the most recent commit, I recently fixed a bug that may be causing your issue.

**Comment by relyanow** [comment]
Sorry for the late response, I updated the code so you shouldn't get this error anymore. Let me know if you run into any other issues.

**Comment by fangli0813** [comment]
Thank you. It works now.
