### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by kautto** [raphael-group/NAIBR#7]
I downloaded the latest commit (2bed0015c2efc57098b3d45d3c2db3b35911dbc8), and now instead of getting the issue in #5 , I'm encountering a type error. The same issue happens whether I run it in multi-threaded or single-threaded mode, although the error message is different:

Multi-threaded (threads = 3)
```
Traceback (most recent call last):
  File "NAIBR.py", line 88, in <module>
    main()
  File "NAIBR.py", line 59, in main
    data = parallel_execute(run_NAIBR,chroms)
  File "src/utils.py", line 385, in parallel_execute
    data = map_fn(function,input_list)
  File "/igm/apps/python/Python-2.7.12_install_static/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/igm/apps/python/Python-2.7.12_install_static/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: integer argument expected, got float
```

Single-threaded
```
Traceback (most recent call last):
  File "NAIBR.py", line 88, in <module>
    main()
  File "NAIBR.py", line 59, in main
    data = parallel_execute(run_NAIBR,chroms)
  File "src/utils.py", line 389, in parallel_execute
    data = map(function,input_list)
  File "NAIBR.py", line 30, in run_NAIBR
    reads_by_LR,LRs_by_pos,discs_by_barcode,discs,interchrom_discs,coverage = make_barcodeDict(chrom)
  File "src/get_reads.py", line 76, in make_barcodeDict
    interchrom_discs[(int(peread.chrm,peread.i/r)*r,peread.nextchrm,int(peread.j/r)*r,peread.orient)].append(peread)
TypeError: integer argument expected, got float
```

I'm not sure if they're both the same issue, but I'm assuming they are.

Nothing particularly exciting in my config file:
```
# minimum mapping quality (default=40)
min_mapq=40

# input bam file
bam_file=/KAUTTO_Esko/data/17-0020-04_H1576_Tumor.phased_possorted.bam

# output directory (default=.)
outdir=/KAUTTO_Esko/output/2017-11-27/NAIBR/17-0020-04_H1576_Tumor

# list of intervals not to be intcluded in analysis (default=None)
blacklist=None

# list in BEDPE format of novel adjacencies to be scored by NAIBR (default=None)
candidates=None

# maximum distance between read-pairs in a linked-read (default=10000)
d=10000

# minimum size of structural variant (default=lmax)
min_sv=1000

# number of threads (default=1)
threads=1

# minimum number of barcode overlaps supporting a candidate NA (default = 3)
k=3
```

**Comment by relyanow** [comment]
This should be fixed now. I accidentally introduced the bug while converting to python3 compatibility.

**Comment by kautto** [comment]
Yep, no longer getting the issue with commit 602f3f765306de766bf7e6012f073153e35f1d15!
