### ISSUE TITLE
UnboundLocalError: local variable 'peread' referenced before assignment

### ISSUE THREAD

**Issue by ahgillmo** [raphael-group/NAIBR#9]
When running the example file using command line, as variable assignment error occurs.

python NAIBR.py example/example.config

Traceback (most recent call last):
  File "NAIBR.py", line 88, in <module>
    main()
  File "NAIBR.py", line 52, in main
    scores = flatten(parallel_execute(run_NAIBR_user,cands))
  File "src/utils.py", line 392, in parallel_execute
    data = map(function,input_list)
  File "NAIBR.py", line 19, in run_NAIBR_user
    reads_by_LR,LRs_by_pos,discs_by_barcode,cands,coverage = make_barcodeDict_user(cand)
  File "src/get_reads.py", line 231, in make_barcodeDict_user
    cand = copy.copy(peread)
UnboundLocalError: local variable 'peread' referenced before assignment

**Comment by ZhenNingYoung** [comment]
I have same error.How to solve this problem?
Traceback (most recent call last):
  File "naibr/NAIBR/NAIBR.py", line 88, in <module>
    main()
  File "naibr/NAIBR/NAIBR.py", line 52, in main
    scores = flatten(parallel_execute(run_NAIBR_user,cands))
  File "naibr/NAIBR/src/utils.py", line 388, in parallel_execute
    data = map_fn(function,input_list)
  File "/Python-2.7.17/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Python-2.7.17/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
UnboundLocalError: local variable 'peread' referenced before assignment
